#!/usr/bin/env sh
# Deprecated with husky v9
#. "$(dirname -- "$0")/_/husky.sh"

# Add PATH setup to ensure npx is found
export PATH="/usr/local/bin:$HOME/.npm-global/bin:$HOME/.nvm/versions/node/$(node -v)/bin:$PATH"

# Then run lint-staged if tests pass
node ./node_modules/lint-staged/bin/lint-staged.js --concurrent false
